package io.pleo.antaeus.scheduler.app.exceptions

class NetworkException : Exception("A network error happened please try again.")